name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release Apk Sign
        run: |
          if [ -n "${{ secrets.RELEASE_KEY_ALIAS }}" ] && [ -n "${{ secrets.RELEASE_STORE_PASSWORD }}" ] && [ -n "${{ secrets.RELEASE_KEY_PASSWORD }}" ]; then
            cp -f $GITHUB_WORKSPACE/.github/workflows/TVBoxOSC.jks $GITHUB_WORKSPACE/app/TVBoxOSC.jks
            sed -i '$a\RELEASE_STORE_FILE=./TVBoxOSC.jks'                             $GITHUB_WORKSPACE/gradle.properties
            sed -i "$a\RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}"            $GITHUB_WORKSPACE/gradle.properties
            sed -i "$a\RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}"  $GITHUB_WORKSPACE/gradle.properties
            sed -i "$a\RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}"      $GITHUB_WORKSPACE/gradle.properties
          fi
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
